### ISSUE TITLE
Allow use of Select/Option tags instead of Input fields for filtering

### ISSUE THREAD

**Issue by KrisNick** [tommyp/multifilter#11]
This is a great jquery snippet! However in many cases where I would want to use something like this, the selectable items would be from a database table and not something that the user would enter in free form.

**Comment by tommyp** [comment]
Thanks! The way to do this would be to have the `select` input with all your options and place it's value into a hidden input when the User changes it, which is then the input that triggers the filter.

Hope this helps!

**Comment by tommyp** [comment]
Closing this issue off.
