### ISSUE TITLE
On second keypress Screen blanks all tables rows and cells

### ISSUE THREAD

**Issue by higginbt** [tommyp/multifilter#13]
I'm using this on an aspx page that contains a repeater control and a wizard control.
As part of the wizard I am pullling data from sql and displaying it in a HTML table built on the fly with the hepl of a placeholder.

The repeater contains a table and the wizard containts a table.
When I type my first character into a search field the data is filtered, when I type the second character all the table rows in the repeater and the wizarde control dissapear.

**Comment by tommyp** [comment]
I don't know ASPX so I'm afraid you're on your own with this one. Good luck.
